language: java
jdk:
  - oraclejdk8

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root

services:
  - mysql

test:
   adapter: mysql2
   database: csye6225
   username: root
   encoding: utf8

before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

sudo: false
install: true

script:
  - ./gradlew war
  - ./gradlew test

notifications:
  email:
    recipients:
    - koticha.c@husky.neu.edu
    - merchant.n@husky.neu.edu
    - lalwani.n@husky.neu.edu
    - lakhmani.a@husky.neu.edu