language: java
jdk:
  - oraclejdk8

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root

services:
  - mysql

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war
  - ./gradlew test --info

after_success:
  - mkdir codedeploy
  - zip -r csye6225-webapp.zip build/libs/ROOT.war appspec.yml
  - ls -al
  - mv csye6225-webapp.zip codedeploy/
  - pwd
  - cd codedeploy
  - ls -al
  - pwd

before_deploy:
  - cd ..

deploy:
  - provider: s3
    access_key_id: AKIAIYECRDTJRXB5VBAA
    secret_access_key:
      secure: VQSVSFp9zGCmy/iqwuxGWSbl6FLSG4a5RWZazhlzxR/MJZU7qktZPHmQbS5EjjQSKIlTiMGj8UqlVdNF4TnGzk8kCSK9AbEZCoXQRidK3TsuXnWzG3HVaksS7JGOlOHUsBnhmqhmZwPRmvMP11MYWsPFrqzzV6AngAHN5Nul8K23iIPHVQRiavnSyniPDIHaujGGcsFAPIpaZlgUohIXatlxAhrLRoz7o6c8cZRmE4kiaJiuIp4ZCGWrkMtFTQ+hM93KjJD3WKm/P8JS6JU+R6AzOdxOAUlW5od3AfrF+r3TEouylLil819Sz4v9Q9t4XnFzoJ1qXvH47sVReqMOuKwzgls//+Q7yQGvdPKQaRqTsmwuRPxVATBwSktYqZmxoopENhXk+FpydtDn/RELK26BCXbD0nwZhai4ZHBfkne9RAVO7o4hfr4pNBeKrGLxTRAxSdLsyM0MDnIOZFfwxULVXWHjyGZphKrj6vSfK94mRJfNrcaqHn1I3W4I8VQaenZXR7cMufoZV3/VilHcKLXR38p8l9q5pPE4frrvlodk+jKR/LMwMfumC7j0pnFdbzFU8wu/hOyiG/BkTz5Rpcr3Hxs8AihJ9L9YxaudU+5HOWJ4StUCvAUvTZYjNGfnSMfZcRfahMtiB7NTFdUdc6ZyHu+SEoIQUOGzrtblon4=
    local_dir: codedeploy
    bucket: code-deploy.csye6225.com
    region: us-east-1
    skip_cleanup: true
    on:
      all_branches: true

notifications:
  email:
    recipients:
    - koticha.c@husky.neu.edu
    - merchant.n@husky.neu.edu
    - lalwani.n@husky.neu.edu
    - lakhmani.a@husky.neu.edu

    on_success: always
    on_failure: always 