language: java
jdk:
  - oraclejdk8

env:
  - MYSQL_HOST=127.0.0.1 MYSQL_USER=root

services:
  - mysql

sudo: false
install: true

script:
  - ./gradlew build
  - ./gradlew war
  - ./gradlew test --info
  - mkdir codedeploy
  - zip -r csye6225-webapp-${TRAVIS_JOB_NUMBER}.zip build/libs/ROOT.war appspec.yml restartTomcat.sh
  - ls -al
  - mv csye6225-webapp-${TRAVIS_JOB_NUMBER}.zip codedeploy/
  - ls -al
  - pwd
  - cd codedeploy
  - ls -al
  - pwd
  - cd ..

deploy:
  - provider: s3
    access_key_id: $access_key_id
    secret_access_key: $secret_access_key
    local_dir: codedeploy
    bucket: $bucket
    region: us-east-1
    skip_cleanup: true
    on:
      all_branches: true
  - provider: codedeploy
    access_key_id: $access_key_id
    bucket: $bucket
    key: csye6225-webapp-${TRAVIS_JOB_NUMBER}.zip
    bundle_type: zip
    application: csye6225-webapp
    deployment_group: csye6225-webapp
    region: us-east-1
    secret_access_key: $secret_access_key
    wait-until-deployed: true
    on:
      all_branches: true


notifications:
  email:
    recipients:
    - koticha.c@husky.neu.edu
    - merchant.n@husky.neu.edu
    - lalwani.n@husky.neu.edu
    - lakhmani.a@husky.neu.edu

    on_success: always
    on_failure: always