language: java
jdk:
  - oraclejdk8

sudo: false
install: true

script:
  - ./gradlew war

notifications:
  email:
    recipients:
    - koticha.c@husky.neu.edu
    - merchant.n@husky.neu.edu
    - lalwani.n@husky.neu.edu
    - lakhmani.a@husky.neu.edu